apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
    plugin: influxdb
  name: monitoring-influxdb
  namespace: kube-system
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    plugin: influxdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    plugin: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      plugin: influxdb
  template:
    metadata:
      labels:
        plugin: influxdb
    spec:
      containers:
      - name: monitoring-influxdb
        image: 192.168.1.55/tenx_containers/heapster-influxdb-amd64:v1.1.1-alpine
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - 'sleep 20 && curl -XPOST "http://127.0.0.1:8086/query"
              --data-urlencode "db=k8s" --data-urlencode "q=create database k8s
              with name \"default\";ALTER RETENTION POLICY default ON k8s
              DURATION 1h REPLICATION 1 SHARD DURATION 1h DEFAULT"'
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
