apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-elk
  namespace: kube-system
  labels:
    k8s-app: fluentd-elk
    kubernetes.io/cluster-service: "true"
    component: fluentd-elk
    tier: control-plane
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-elk
        kubernetes.io/cluster-service: "true"
        component: fluentd-elk
        tier: control-plane
    spec:
      containers:
      - name: fluentd-elk
        image: 192.168.1.12/test_containers/fluentd-elasticsearch:hosting
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
