kind: Service
apiVersion: v1
metadata:
  name: prometheus-1
  namespace: kube-system
  labels:
    plugin: prometheus-1
spec:
  type: NodePort
  ports:
  - name: prometheus-1
    protocol: TCP
    port: 9090
    nodePort: 30903
  selector:
    plugin: prometheus-1
