apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: prometheus-config
data:
  prometheus.yaml: |
    # global:
    #   external_labels:
    #     datacenter: eu-west-1
    scrape_configs:
    - job_name: 'kubernetes-services'
      params:
        module: [http_2xx]
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]   # <k8s-app> 为label中key
        action: keep
        regex: kube-system                # label中<k8s-app> 对应的value

# 注意点：action 使用keep

# 自定义服务metrics,主要设置三点，metric_path, source_labels, 和regex；
#       - job_name: 'kubernetes-services'
#         kubernetes_sd_configs:
#           - role: service
#             relabel_configs:
#               metrics_path: /probe   # 自定义metrics path
#               - source_labels: [__meta_kubernetes_service_name]  # 要设置成__meta_kubernetes_service_name
#                 action: keep
#                 regex: serviceName                # service Name
