apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-10-19T03:12:23Z
  generation: 1
  labels:
    kubernetes.io/cluster-service: "true"
    plugin: elasticsearch-logging
    version: v1
  name: elasticsearch-logging
  namespace: kube-system
  resourceVersion: "151775"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/elasticsearch-logging
  uid: 53dc253d-b47b-11e7-b29f-005056854b41
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      plugin: elasticsearch-logging
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubernetes.io/cluster-service: "true"
        plugin: elasticsearch-logging
        version: v1
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: 192.168.2.8/tenx_containers/elasticsearch:5.5
        imagePullPolicy: IfNotPresent
        name: elasticsearch-logging
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: elasticsearch-logging
      serviceAccountName: elasticsearch-logging
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /tenxcloud/es_data
        name: es-persistent-storage
