apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-assist
  namespace: kube-system
  labels:
    k8s-app: fluentd-assist
    kubernetes.io/cluster-service: "true"
    component: fluentd-assist
    tier: control-plane
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-assist
        kubernetes.io/cluster-service: "true"
        component: fluentd-assist
        tier: control-plane
    spec:
      containers:
      - name: fluentd-assist
        image: 192.168.1.12/tenx_containers/fluentd-assist:v1.0.1
        command:
        - /start.sh
        - --logtostderr -v=6
        terminationMessagePath: /dev/termination-log
        imagePullPolicy: IfNotPresent
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        - mountPath: /var/lib/kubelet
          name: varlibkubelet
        resources:
          limits:
            memory: "500Mi"
            cpu: "400m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlibkubelet
        hostPath:
          path: /var/lib/kubelet
