apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: prometheus-config-federate  # configmap name
data:
  prometheus.yaml: |
    scrape_configs:
    - job_name: 'prom-federation'  # prometheus 创建的job名称
      honor_labels: true           #设置为true，则表示保持抓取过来的数据格式不变
      metrics_path: /federate      # the /federate endpoint allows retrieving the current value for a selected set of time series in that server
      params:
        match[]:
          - '{job=~".+"}'          # Request all job-level time series
      static_configs:
        - targets:
            - 'prometheus:9090'    # target server list
