apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: prometheus-deployment
    plugin: prometheus
    app: prometheus
  name: prometheus
  namespace: kube-system
spec:
  selector:
    matchLabels:
      plugin: prometheus
  template:
    metadata:
      labels:
        plugin: prometheus
    spec:
      containers:
      - image: 192.168.1.52/tenx_containers/prometheus:v1.6.1
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 300Mi
        name: prometheus
        command:
        - "/bin/prometheus"
        args:
        - "-config.file=/etc/prometheus/prometheus.yaml"
        - "-storage.local.path=/prometheus"
        - "-storage.local.retention=24h"
        - "-alertmanager.url=http://alertmanager:9093"
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: rules-volume
          mountPath: "/etc/prometheus_rules"
        - mountPath: "/prometheus"
          name: data
        - mountPath: "/etc/prometheus"
          name: config-volume
        - name: tenxcloud-time-localtime
          readOnly: true
          mountPath: "/etc/localtime"
        - name: tenxcloud-time-zone
          readOnly: true
          mountPath: "/etc/timezone"
      - image: 192.168.1.52/tenx_containers/inotify:1.0
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
        name: notify
        args:
        - 'while inotifywait -qq -e modify,create,delete /etc/prometheus_rules/..data/;
          do sh -c  "curl -X POST http://localhost:9090/-/reload"; done; '
        volumeMounts:
        - name: rules-volume
          mountPath: "/etc/prometheus_rules"
      volumes:
      - emptyDir: {}
        name: data
      - name: rules-volume
        configMap:
          name: prometheus-rules
          defaultMode: 420
      - configMap:
          name: prometheus-config
        name: config-volume
      - name: tenxcloud-time-localtime
        hostPath:
          path: "/etc/localtime"
      - name: tenxcloud-time-zone
        hostPath:
          path: "/etc/timezone"
