kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: system:controller:nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
    nmespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:controller:nfs-provisioner
  apiGroup: rbac.authorization.k8s.io
