apiVersion: v1
kind: Service
metadata:
  annotations:
    tenxcloud.com/schemaPortname: {{name}}/TCP
  name: {{external-name}}
  labels:
    app: {{external-name}}
spec:
  ports:
  - port: 2379
    name: {{name}}
  selector:
    app: {{name}}
  externalIPs:
    - {{external-ip}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{name}}
  labels:
    app: {{name}}
spec:
  ports:
  - port: 2380
    name: peer
  clusterIP: None
  selector:
    app: {{name}}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{name}}
spec:
  serviceName: {{name}}
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        app: {{name}}
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: {{name}}
        image: {{registry}}/tenx_containers/etcd-pet:3.2.4
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SERVICE_NAME
          value: {{name}}
        - name: CLUSTER_NAME
          value: {{name}}
        ports:
        - name: peer
          containerPort: 2380
        - name: {{name}}
          containerPort: 2379
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "curl http://127.0.0.1:2379/health 2>&1"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/etcd
        resources:
          limits:
            memory: '2048Mi'
          requests:
            cpu: 500m
            memory: '512Mi'
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: tenx-rbd
      resources:
        requests:
          storage: {{size}}Mi
