apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysqltest
  namespace: kube-system
spec:
  serviceName: mysqltest
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqltest
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
            {
                "name": "install",
                "image": "192.168.1.52/tenx_containers/galera-install:utf8",
                "imagePullPolicy": "Always",
                "args": ["--work-dir=/work-dir"],
                "volumeMounts": [
                    {
                        "name": "workdir",
                        "mountPath": "/work-dir"
                    },
                    {
                        "name": "config",
                        "mountPath": "/etc/mysql"
                    }
                ]
            },
            {
                "name": "bootstrap",
                "image": "192.168.1.52/tenx_containers/debian:jessie",
                "command": ["/work-dir/peer-finder"],
                "args": ["-on-start=\"/work-dir/on-start.sh\"", "-service=mysqltest"],
                "env": [
                  {
                      "name": "POD_NAMESPACE",
                      "valueFrom": {
                          "fieldRef": {
                              "apiVersion": "v1",
                              "fieldPath": "metadata.namespace"
                          }
                      }
                   }
                ],
                "volumeMounts": [
                    {
                        "name": "workdir",
                        "mountPath": "/work-dir"
                    },
                    {
                        "name": "config",
                        "mountPath": "/etc/mysql"
                    }
                ]
            }
        ]'
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: mysqltest
        image: 192.168.1.52/tenx_containers/mysql-galera:e2e
        ports:
        - containerPort: 3306
          name: mysqltest
        - containerPort: 4444
          name: sst
        - containerPort: 4567
          name: replication
        - containerPort: 4568
          name: ist
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123123"
        resources:
          limits:
            memory: '512Mi'
          requests:
            cpu: 50m
            memory: '512Mi'
        args:
        - --defaults-file=/etc/mysql/my-galera.cnf
        - --user=root
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/
        - name: config
          mountPath: /etc/mysql
      volumes:
      - name: config
        emptyDir: {}
      - name: workdir
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteMany" ]
      # accessModes: [ "ReadOnlyMany" ]
      # accessModes: [ "ReadWriteOnce" ]
      storageClassName: tenx-rbd
      resources:
        requests:
          storage: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tenxcloud.com/schemaPortname: mysqltest/TCP
    system/lbgroup: none
  name: mysqltest-pgytt
  namespace: kube-system
  labels:
    app: mysqltest-pgytt
spec:
  ports:
    - port: 3306
      name: mysqltest
  selector:
    app: mysqltest
  externalIPs:
    - 11.11.1.1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: mysqltest
  namespace: kube-system
  labels:
    app: mysqltest
spec:
  ports:
  - port: 3306
    name: mysqltest
  clusterIP: None
  selector:
    app: mysqltest
