apiVersion: v1
kind: Service
metadata:
  annotations:
    tenxcloud.com/schemaPortname: {{name}}/TCP
  name: {{external-name}}
  labels:
    app: {{external-name}}
spec:
  ports:
  - port: 6379
    name: {{name}}
  selector:
    app: {{name}}
  externalIPs:
    - {{external-ip}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{name}}
  labels:
    app: {{name}}
spec:
  ports:
  - port: 6379
    name: peer
  # *.redis.default.svc.cluster.local
  clusterIP: None
  selector:
    app: {{name}}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{name}}
spec:
  serviceName: {{name}}
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        app: {{name}}
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
            {
                "name": "install",
                "image": "{{registry}}/tenx_containers/redis-install:0.2",
                "imagePullPolicy": "Always",
                "args": ["--install-into=/opt", "--work-dir=/work-dir"],
                "env": [
                  {
                      "name": "REDIS_PASSWORD",
                      "value": "{{password}}"
                   }
                ],
                "volumeMounts": [
                    {
                        "name": "opt",
                        "mountPath": "/opt"
                    },
                    {
                        "name": "workdir",
                        "mountPath": "/work-dir"
                    }
                ]
            },
            {
                "name": "bootstrap",
                "image": "{{registry}}/tenx_containers/debian:jessie",
                "command": ["/work-dir/peer-finder"],
                "args": ["-on-start=\"/work-dir/on-start.sh\"", "-service={{name}}"],
                "env": [
                  {
                      "name": "POD_NAMESPACE",
                      "valueFrom": {
                          "fieldRef": {
                              "apiVersion": "v1",
                              "fieldPath": "metadata.namespace"
                          }
                      }
                   }
                ],
                "volumeMounts": [
                    {
                        "name": "opt",
                        "mountPath": "/opt"
                    },
                    {
                        "name": "workdir",
                        "mountPath": "/work-dir"
                    }
                ]
            }
        ]'
    spec:
      containers:
      - name: {{name}}
        image: {{registry}}/tenx_containers/debian:jessie
        ports:
        - containerPort: 6379
          name: peer
        resources:
          limits:
            memory: '512Mi'
          requests:
            cpu: 250m
            memory: '512Mi'
        command:
        - /opt/redis/redis-server
        args:
        - /opt/redis/redis.conf
        volumeMounts:
        - name: datadir
          mountPath: /data
        - name: opt
          mountPath: /opt
      volumes:
      - name: opt
        emptyDir: {}
      - name: workdir
        emptyDir: {}
      - name: datadir
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: tenx-rbd
      resources:
        requests:
          storage: {{size}}Mi
