apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.0.68:6789,192.168.0.55:6789,192.168.0.94:6789,192.168.0.99:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: tenx-pool
  userId: admin
  userSecretName: ceph-secret
