kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: tenx-rbd
  resources:
    requests:
      storage: 3Gi
