apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tenx-rbd-no-secret
  annotations:
      #    storageclass.kubernetes.io/is-default-class: "true"    # 是否为default
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.0.68:6789,192.168.0.55:6789,192.168.0.94:6789
  adminId: admin
  adminSecretName: ceph-secret-nosecret
  adminSecretNamespace: "kube-system" 
  pool: tenx-pool   # ceph pool
  userId: admin
  userSecretName: ceph-secret-nosecret # The name of Ceph Secret for userId to map RBD image. It must exist in the same namespace as PVCs
  imageFormat: "2"
  imageFeatures: "1"
