kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: no-mount-pvc
  namespace: song1
  labels:
    tenxcloud.com/fsType: ext4 
    tenxcloud.com/storageType: ceph 
    texncloud.com/srType: private 
    tenxcloud.com/reclaimPolicy: delete 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tenx-rbd
  resources:
    requests:
      storage: 3Gi
