kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  namespace: abcdef
  labels:
    type: local
spec:
  storageClassName: tenx-rbd
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
